from application import *

print("*************************")
print("People: ")
Person1 = Person(1, "Bucur", "Bianca", 20, "Student")
Person2 = Person(2, "Varone", "Paola", 35, "Teacher")
Person3 = Person(3, "Tamanini", "Damiano", 19, "Student")
Person4 = Person(4, "Spinieli", "Angelica", 40, "Teacher")
Person5 = Person(5, "Candido", "Valeria", 55, "Teacher")
Person6 = Person(6, "Zeni", "Luca", 18, "Student")
Person7 = Person(7, "Gaddo", "Luca", 16, "Student")
Person8 = Person(8, "Patton", "Alessandra", 17, "Student")
print(Person1)
print(Person2)
print(Person3)
print("*************************")
print("Students: ")
Student1 = Student(1, "Bucur", "Bianca", 20, "Student")
Student2 = Student(3, "Tamanini", "Damiano", 19, "Student")
Student3 = Student(6, "Zeni", "Luca", 18, "Student")
Student4 = Student(7, "Gaddo", "Luca", 16, "Student")
Student5 = Student(8, "Patton", "Alessandra", 17, "Student")
print(Student1)
print(Student2)
print(Student3)
print(Student4)
print(Student5)
print("*************************")
print("Teachers: ")
Teachers1 = Teacher(2, "Varone", "Paola", 35, "Teacher")
Teachers2 = Teacher(4, "Spinieli", "Angelica", 40, "Teacher")
Teachers3 = Teacher(5, "Candido", "Valeria", 55, "Teacher")


